
app:
  image: wordpress/php-fpm
  volumes_from:
    - data
  links:
    - db
  command: /docker-endpoint.sh

web:
  image: wordpress/nginx
  volumes_from:
    - data
  ports:
    - 80:80
    - 443:443
  environment: []
  command: /docker-endpoint.sh

db:
  image: mariadb:10.1.22
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_USER:     user
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: wordpress

data:
  image: busybox:latest
  volumes:
    - /var/www/wordpress
    - /var/run/php-fpm
    - /var/lib/mysql
  command: /bin/sh
