---
- hosts: localhost
  tasks:
    - name: Create php-fpm container.
      docker_container:
        name: php-base
        image: centos:7
        command: /bin/bash
        tty: yes
        state: started

- hosts: php-base
  connection: docker
  pre_tasks:
    - name: Add web user.
      user:
        name: webuser
        uid: 1000
        shell: /bin/sh
  roles:
    - role: shomatan.php-fpm
      php_fpm_pool_user: webuser
      php_fpm_pool_group: webuser
    - role: shomatan.wp-cli
  tasks:
    - name: Copy docker endpoint script.
      template:
        src: docker-endpoint.sh.j2
        dest: /docker-endpoint.sh
        mode: 0755
        
- hosts: localhost
  connection: local
  tasks:
    - local_action: shell /usr/local/bin/docker commit php-base wordpress/php-fpm
