---
- hosts: php-base
  connection: docker
  pre_tasks:
    - name: Add web user.
      user:
        name: webuser
        uid: 1000
        shell: /bin/sh
  roles:
    - role: shomatan.php-fpm
      php_fpm_pool_user: webuser
      php_fpm_pool_group: webuser
    - role: shomatan.wp-cli
  tasks:
    - name: Copy docker endpoint script.
      template:
        src: docker-endpoint.sh.j2
        dest: /docker-endpoint.sh
        mode: 0755
