---
- hosts: web-base
  connection: docker
  pre_tasks:
    - name: Add web user.
      user:
        name: webuser
        uid: 1000
        shell: /bin/sh
  roles:
    - role: shomatan.nginx
      nginx_user: webuser
  tasks:
    - name: Copy wordpress config for nginx.
      template:
        src: wordpress.conf.j2
        dest: /etc/nginx/conf.d/wordpress.conf

    - name: Copy docker endpoint script.
      template:
        src: docker-endpoint.sh.j2
        dest: /docker-endpoint.sh
        mode: 0755

- hosts: localhost
  connection: local
  tasks:
    - local_action: shell /usr/local/bin/docker commit web-base wordpress/nginx
